### ISSUE TITLE
First release! 

### ISSUE THREAD

**Issue by enoch85** [ezraholm50/BerryCloud#51]
**Todo:** 

- [ ] Make sure everything is working
- [ ] Publish download page and link the VM (link is in the shared folder)
- [ ] Write a nice blog post about it
- [ ] Twitter, Facebook
- [ ] Celebrate!

@ezraholm50

**Comment by enoch85** [comment]
Any update here? @ezraholm50

**Comment by ezraholm50** [comment]
Still polishing the last remaining bugs and general look during install. Also made the installation time smaller by installing more stuff that can already be installed.

**Comment by enoch85** [comment]
@ezraholm50 Nice! Any ETA? Just want to be done with this so we can move forward. :)
